FROM gradle:7.6-jdk17 AS builder
WORKDIR /app
COPY services/ledger .
RUN ./gradlew bootJar --no-daemon

FROM openjdk:17-ea-17-slim
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]

