FROM gradle:7.6-jdk17 AS builder
WORKDIR /app
COPY services/payments .
RUN ./gradlew bootJar --no-daemon

FROM openjdk:17-ea-17-slim
EXPOSE 8080
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

